import {
  Twitter,
  Github,
  Linkedin,
  Instagram,
  Youtube,
  Facebook,
  Globe,
  Mail,
  Phone,
  MapPin,
  Calendar,
  Heart,
  Star,
  Home,
  User,
  Settings,
  Link,
  ExternalLink,
  Download,
  Upload,
  Share2,
  Copy,
  Edit,
  Trash2,
  Plus,
  Minus,
  Check,
  X,
  AlertCircle,
  Info,
  HelpCircle,
  Search,
  Filter,
  Grid,
  List,
  Eye,
  EyeOff,
  Lock,
  Unlock,
  Key,
  Shield,
  Camera,
  Image,
  Video,
  Music,
  File,
  Folder,
  Database,
  Server,
  Cloud,
  Wifi,
  Bluetooth,
  Smartphone,
  Tablet,
  Monitor,
  Laptop,
  Printer,
  Keyboard,
  Mouse,
  Headphones,
  Speaker,
  Gamepad2,
  Puzzle,
  Trophy,
  Medal,
  Award,
  Gift,
  Package,
  ShoppingCart,
  CreditCard,
  DollarSign,
  Euro,
  Bitcoin,
  TrendingUp,
  TrendingDown,
  BarChart3,
  PieChart,
  Activity,
  Zap,
  Target,
  Flag,
  Bookmark,
  Tag,
  Hash,
  AtSign,
  Percent,
  Infinity,
  Pi,
  Sigma,
  Omega,
  // Add more icons as needed
} from 'lucide-react';

export const iconMap: Record<string, any> = {
  // Social Media
  twitter: Twitter,
  github: Github,
  linkedin: Linkedin,
  instagram: Instagram,
  youtube: Youtube,
  facebook: Facebook,
  
  // General
  globe: Globe,
  mail: Mail,
  phone: Phone,
  mapPin: MapPin,
  calendar: Calendar,
  heart: Heart,
  star: Star,
  home: Home,
  user: User,
  settings: Settings,
  link: Link,
  externalLink: ExternalLink,
  
  // Actions
  download: Download,
  upload: Upload,
  share: Share2,
  copy: Copy,
  edit: Edit,
  trash: Trash2,
  plus: Plus,
  minus: Minus,
  check: Check,
  x: X,
  
  // UI
  alertCircle: AlertCircle,
  info: Info,
  helpCircle: HelpCircle,
  search: Search,
  filter: Filter,
  grid: Grid,
  list: List,
  eye: Eye,
  eyeOff: EyeOff,
  
  // Security
  lock: Lock,
  unlock: Unlock,
  key: Key,
  shield: Shield,
  
  // Media
  camera: Camera,
  image: Image,
  video: Video,
  music: Music,
  
  // Files
  file: File,
  folder: Folder,
  database: Database,
  server: Server,
  cloud: Cloud,
  
  // Technology
  wifi: Wifi,
  bluetooth: Bluetooth,
  smartphone: Smartphone,
  tablet: Tablet,
  monitor: Monitor,
  laptop: Laptop,
  printer: Printer,
  keyboard: Keyboard,
  mouse: Mouse,
  headphones: Headphones,
  speaker: Speaker,
  
  // Gaming
  gamepad: Gamepad2,
  puzzle: Puzzle,
  trophy: Trophy,
  medal: Medal,
  award: Award,
  
  // Commerce
  gift: Gift,
  package: Package,
  shoppingCart: ShoppingCart,
  creditCard: CreditCard,
  dollarSign: DollarSign,
  euro: Euro,
  bitcoin: Bitcoin,
  
  // Analytics
  trendingUp: TrendingUp,
  trendingDown: TrendingDown,
  barChart: BarChart3,
  pieChart: PieChart,
  activity: Activity,
  
  // Symbols
  zap: Zap,
  target: Target,
  flag: Flag,
  bookmark: Bookmark,
  tag: Tag,
  hash: Hash,
  atSign: AtSign,
  percent: Percent,
  infinity: Infinity,
  pi: Pi,
  sigma: Sigma,
  omega: Omega,
};

export function getIcon(iconId: string) {
  return iconMap[iconId] || Globe; // Default to Globe if icon not found
}

export function getIconList() {
  return Object.keys(iconMap);
} 