// Centralized icon list for the application
// This file contains all available icons that can be used throughout the app

export const ICON_LIST = [
  // Social Media (Lucide)
  'twitter',
  'github',
  'linkedin',
  'instagram',
  'youtube',
  'facebook',
  
  // Social Media (Simple Icons)
  'tiktok',
  'discord',
  'twitch',
  'reddit',
  'snapchat',
  'whatsapp',
  'telegram',
  'spotify',
  'pinterest',
  'tumblr',
  'vimeo',
  'dailymotion',
  'vk',
  'wechat',
  'line',
  'kakao',
  'naver',
  
  // Tech Platforms
  'stackoverflow',
  'medium',
  'hashnode',
  'substack',
  'notion',
  'figma',
  'slack',
  'zoom',
  
  // Cloud & Storage
  'dropbox',
  'googledrive',
  'box',
  'evernote',
  'trello',
  'asana',
  'jira',
  'confluence',
  'bitbucket',
  'gitlab',
  
  // Development & DevOps
  'docker',
  'kubernetes',
  'heroku',
  'vercel',
  'netlify',
  'cloudflare',
  'digitalocean',
  'vultr',
  
  // Payment & E-commerce
  'stripe',
  'paypal',
  'square',
  'shopify',
  'woo',
  'prestashop',
  
  // CMS & Website Builders
  'wordpress',
  'drupal',
  'joomla',
  'wix',
  'squarespace',
  'webflow',
  
  // Automation & IoT
  'zapier',
  'ifttt',
  'make',
  'n8n',
  'nodered',
  'homeassistant',
  'openhab',
  'homebridge',
  'tasmota',
  'esphome',
  
  // Hardware & IoT
  'arduino',
  'raspberrypi',
  'arm',
  'intel',
  'amd',
  'nvidia',
  'qualcomm',
  'mediatek',
  'broadcom',
  'stmicroelectronics',
  'nxp',
  'samsung',
  'lg',
  'sony',
  'sharp',
  'toshiba',
  'hitachi',
  'mitsubishi',
  'fujitsu',
  'nec',
  'epson',
  'hp',
  'dell',
  'lenovo',
  'asus',
  'acer',
  'msi',
  'corsair',
  'coolermaster',
  'nzxt',
  'seasonic',
  'fsp',
  'biostar',
  'ecs',
  'foxconn',
  
  // General
  'globe',
  'mail',
  'phone',
  'mapPin',
  'calendar',
  'heart',
  'star',
  'home',
  'user',
  'settings',
  'link',
  'externalLink',
  
  // Actions
  'download',
  'upload',
  'share',
  'copy',
  'edit',
  'trash',
  'plus',
  'minus',
  'check',
  'x',
  
  // UI
  'alertCircle',
  'info',
  'helpCircle',
  'search',
  'filter',
  'grid',
  'list',
  'eye',
  'eyeOff',
  
  // Security
  'lock',
  'unlock',
  'key',
  'shield',
  
  // Media
  'camera',
  'image',
  'video',
  'music',
  
  // Files
  'file',
  'folder',
  'database',
  'server',
  'cloud',
  
  // Technology
  'wifi',
  'bluetooth',
  'smartphone',
  'tablet',
  'monitor',
  'laptop',
  'printer',
  'keyboard',
  'mouse',
  'headphones',
  'speaker',
  
  // Gaming
  'gamepad',
  'puzzle',
  'trophy',
  'medal',
  'award',
  
  // Commerce
  'gift',
  'package',
  'shoppingCart',
  'creditCard',
  'dollarSign',
  'euro',
  'bitcoin',
  
  // Analytics
  'trendingUp',
  'trendingDown',
  'barChart',
  'pieChart',
  'activity',
  
  // Symbols
  'zap',
  'target',
  'flag',
  'bookmark',
  'tag',
  'hash',
  'atSign',
  'percent',
  'infinity',
  'pi',
  'sigma',
  'omega',
] as const;

export type IconName = typeof ICON_LIST[number];

// Icon categories for better organization
export const ICON_CATEGORIES = {
  'Social Media': ['twitter', 'github', 'linkedin', 'instagram', 'youtube', 'facebook', 'tiktok', 'discord', 'twitch', 'reddit', 'snapchat', 'whatsapp', 'telegram', 'spotify', 'pinterest', 'tumblr', 'vimeo', 'dailymotion', 'vk', 'wechat', 'line', 'kakao', 'naver'],
  'Tech Platforms': ['stackoverflow', 'medium', 'hashnode', 'substack', 'notion', 'figma', 'slack', 'zoom'],
  'Cloud & Storage': ['dropbox', 'googledrive', 'box', 'evernote', 'trello', 'asana', 'jira', 'confluence', 'bitbucket', 'gitlab'],
  'Development & DevOps': ['docker', 'kubernetes', 'heroku', 'vercel', 'netlify', 'cloudflare', 'digitalocean', 'vultr'],
  'Payment & E-commerce': ['stripe', 'paypal', 'square', 'shopify', 'woo', 'prestashop'],
  'CMS & Website Builders': ['wordpress', 'drupal', 'joomla', 'wix', 'squarespace', 'webflow'],
  'Automation & IoT': ['zapier', 'ifttt', 'make', 'n8n', 'nodered', 'homeassistant', 'openhab', 'homebridge', 'tasmota', 'esphome'],
  'Hardware & IoT': ['arduino', 'raspberrypi', 'arm', 'intel', 'amd', 'nvidia', 'qualcomm', 'mediatek', 'broadcom', 'stmicroelectronics', 'nxp', 'samsung', 'lg', 'sony', 'sharp', 'toshiba', 'hitachi', 'mitsubishi', 'fujitsu', 'nec', 'epson', 'hp', 'dell', 'lenovo', 'asus', 'acer', 'msi', 'corsair', 'coolermaster', 'nzxt', 'seasonic', 'fsp', 'biostar', 'ecs', 'foxconn'],
  'General': ['globe', 'mail', 'phone', 'mapPin', 'calendar', 'heart', 'star', 'home', 'user', 'settings', 'link', 'externalLink'],
  'Actions': ['download', 'upload', 'share', 'copy', 'edit', 'trash', 'plus', 'minus', 'check', 'x'],
  'UI': ['alertCircle', 'info', 'helpCircle', 'search', 'filter', 'grid', 'list', 'eye', 'eyeOff'],
  'Security': ['lock', 'unlock', 'key', 'shield'],
  'Media': ['camera', 'image', 'video', 'music'],
  'Files': ['file', 'folder', 'database', 'server', 'cloud'],
  'Technology': ['wifi', 'bluetooth', 'smartphone', 'tablet', 'monitor', 'laptop', 'printer', 'keyboard', 'mouse', 'headphones', 'speaker'],
  'Gaming': ['gamepad', 'puzzle', 'trophy', 'medal', 'award'],
  'Commerce': ['gift', 'package', 'shoppingCart', 'creditCard', 'dollarSign', 'euro', 'bitcoin'],
  'Analytics': ['trendingUp', 'trendingDown', 'barChart', 'pieChart', 'activity'],
  'Symbols': ['zap', 'target', 'flag', 'bookmark', 'tag', 'hash', 'atSign', 'percent', 'infinity', 'pi', 'sigma', 'omega'],
} as const; 